---
- name: Setup Commons Prerequisite
  hosts:
    - node
    - master
  gather_facts: yes
  roles:
    - { role: prereq-setup }
  tags:
    - setup

- name: Tools Prerequisite
  hosts:
    - master
    - node
  gather_facts: yes
  roles:
    - { role: prereq-tools }
  tags:
    - tools

- name: Configure Main Node
  hosts:
    - master
  gather_facts: yes
  roles:
    - { role: configure-main-node }
  tags:
    - k8smain

- name: Getting cluster info
  hosts:
    - master
  gather_facts: yes
  roles:
    - { role: getting-cluster-info }
  tags:
    - addnode

- name: Add Worker Node
  hosts:
    - node
  gather_facts: yes
  roles:
    - { role: configure-worker-node }
  tags:
    - addnode

### deprecated !
- name: Add features like Dashboard, ingress, etc
  hosts:
    - master
  gather_facts: yes
  roles:
    - { role: features }
  tags:
    - addfeatures
