---
- name: Update system
  become: true
  shell: yum -y update
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Update system
  become: true
  shell: apt -y update
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Ensuring basic requirement and dependencies
  become: yes
  shell: yum -y install wget vim git curl net-tools bind-utils yum-utils libselinux-python
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Ensuring basic requirement and dependencies
  become: true
  shell: apt -y install wget vim git curl net-tools apt-transport-https ca-certificates gnupg lsb-release
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Set SELinux to disabled state
  become: yes
  selinux:
    state: disabled
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Enable IPv4 forwarding
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  become: yes
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes

- name: Disable swap
  become: yes
  shell: swapoff -a
