#19.03.15
ansible_user: "ubuntu"

docker_version: "5:19.03.15~3-0~ubuntu-"
## 1.19.10-0 para centos
k8s_version: "1.19.10-00"
k8s_packages:
  - "kubectl"
  - "kubeadm"
  - "kubelet"

## master vars
k8s_network_cidr: "10.244.0.0/16"
k8s_prefliht_ignore: "all"
k8s_init_options: "--pod-network-cidr={{ k8s_network_cidr }} --ignore-preflight-errors={{ k8s_prefliht_ignore }}"
k8s_flannel_yml: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

### node vars
k8s_join_token: "--token={{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"
k8s_join_hash: "--discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}"
master_internal_ip: "{{ hostvars['K8S_TOKEN_HOLDER']['ip'] }}"
k8s_join_options: "{{ k8s_join_token }} {{ k8s_join_hash }}"
