---
# - name: Update system
#   become: true
#   shell: yum -y update

- name: Ensuring basic requirement and dependencies
  become: yes
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - wget
      - git
      - curl
      - net-tools
      - bind-utils
      - yum-utils
    state: present

- name: Set SELinux to disabled state
  become: yes
  selinux:
    state: disabled
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Enable IPv4 forwarding
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  become: yes
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes

- name: Disable swap
  become: yes
  shell: swapoff -a
